[build]
  command = "pnpm build"
  publish = ".output/public"

[build.environment]
  NODE_OPTIONS = "--max-old-space-size=8192"
  NITRO_PRESET = "netlify"

[functions]
  directory = ".output/server"

[[redirects]]
  from = "/_studio"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/_studio/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/__nuxt_studio/*"
  to = "/.netlify/functions/server"
  status = 200
